ARG DB_TYPE
ARG DATABASE_URL

# Build stage
FROM rust:1.75-alpine AS builder
RUN apk add --no-cache openssl-dev musl-dev
WORKDIR /app
COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl

# Runtime stage
FROM alpine:3.19
RUN apk add --no-cache openssl
WORKDIR /app
COPY --from=builder /app/target/release/rust_chat /app/
USER 1000:1000
EXPOSE 3030
CMD ["./rust_chat"]
